dataset_name: cullpdb

model_name: customcnn

epochs: 300
learning_rate: 0.001

checkpoint_path: results/ckpts/cullpdb_customcnn.pt
logs_path: results/logs/cullpdb_customcnn.txt
curves_path: results/curves/cullpdb_customcnn.png

test_report_path: results/test/cullpdb_customcnn_report.txt
test_alignment_path: results/test/cullpdb_customcnn_alignment.txt